config/routes.rb
Rails.application.routes.draw do
  resources :air_monitor_databases

  get 'home/index'
  get 'home' => 'home#index'

  root :to => 'home#index'

end

app/models/air_monitor_database.rb
class AirMonitorDatabase < ActiveRecord::Base
end

app/controllers/air_monitor_databases_controller.rb
class AirMonitorDatabasesController < ApplicationController
  before_action :set_air_monitor_database, only: [:show, :edit, :update, :destroy]

  # GET /air_monitor_databases
  # GET /air_monitor_databases.json
  def index
    @air_monitor_databases = AirMonitorDatabase.all
  end

  # GET /air_monitor_databases/1
  # GET /air_monitor_databases/1.json
  def show
  end

  # GET /air_monitor_databases/new
  def new
    @air_monitor_database = AirMonitorDatabase.new
  end

  # GET /air_monitor_databases/1/edit
  def edit
  end

  # POST /air_monitor_databases
  # POST /air_monitor_databases.json
  def create
    @air_monitor_database = AirMonitorDatabase.new(air_monitor_database_params)

    respond_to do |format|
      if @air_monitor_database.save
        format.html { redirect_to @air_monitor_database, notice: 'Air monitor record was successfully created.' }
        format.json { render :show, status: :created, location: @air_monitor_database }
      else
        format.html { render :new }
        format.json { render json: @air_monitor_database.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /air_monitor_databases/1
  # PATCH/PUT /air_monitor_databases/1.json
  def update
    respond_to do |format|
      if @air_monitor_database.update(air_monitor_database_params)
        format.html { redirect_to @air_monitor_database, notice: 'Air monitor record was successfully updated.' }
        format.json { render :show, status: :ok, location: @air_monitor_database }
      else
        format.html { render :edit }
        format.json { render json: @air_monitor_database.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /air_monitor_databases/1
  # DELETE /air_monitor_databases/1.json
  def destroy
    @air_monitor_database.destroy
    respond_to do |format|
      format.html { redirect_to air_monitor_databases_url, notice: 'Air monitor record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_air_monitor_database
      @air_monitor_database = AirMonitorDatabase.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def air_monitor_database_params
      params.require(:air_monitor_database).permit(:pm10data, :noadata, :fieldengineer)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/air_monitor_databases_helper.rb
module AirMonitorDatabasesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/air_monitor_databases/_form.html.erb
<%= form_for(@air_monitor_database) do |f| %>
  <% if @air_monitor_database.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@air_monitor_database.errors.count, "error") %> prohibited this air_monitor_database from being saved:</h2>

      <ul>
      <% @air_monitor_database.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :pm10data, "PM10" %>
    <%= f.text_field :pm10data %>
  </div>
  </br>
  <div class="field">
    <%= f.label :noadata, "NOA", :class => 'strong' %>
    <%= f.text_field :noadata %>
  </div>
  </br>
  <div class="field">
    <%= f.label :fieldengineer, "Field Engineer", :class => 'strong' %>
    <%= f.text_field :fieldengineer %>
  </div>
  </br>
  <div class="actions">
    <%= f.submit "Create Record" %>
  </div>
<% end %>

app/views/air_monitor_databases/edit.html.erb
<h1>Editing air_monitor_database</h1>

<%= render 'form' %>

<%= link_to 'Show', @air_monitor_database %> |
<%= link_to 'Back', air_monitor_databases_path %>

app/views/air_monitor_databases/index.html.haml
= link_to 'Add Record', new_air_monitor_database_path, data: {role: 'button'}
%h1 Listing air monitor records
- @air_monitor_databases.each do |air_monitor_database|
  %div{ data: {role: 'collapsible'}}
    %h3 PM10: #{air_monitor_database.pm10data}
    %h4 NOA: #{air_monitor_database.noadata}
    %h4 Field Engineer: #{air_monitor_database.fieldengineer}
    = link_to 'Edit', edit_air_monitor_database_path(air_monitor_database), data: {role: 'button'}
    = link_to 'Destroy', air_monitor_database, confirm: 'Are you sure?', method: :delete, data: {role: 'button'}

app/views/air_monitor_databases/new.html.erb
<h1>New air monitor record</h1>

<%= render 'form' %>

<%= link_to 'Back', air_monitor_databases_path %>

app/views/air_monitor_databases/show.html.haml
%p#notice= notice
%p
  %strong PM10 Data:
  = @air_monitor_database.pm10data
%p
  %strong NOA Data:
  = @air_monitor_database.noadata
%p
  %strong Field Engineer:
  = @air_monitor_database.fieldengineer
= link_to 'Edit', edit_air_monitor_database_path(@air_monitor_database), data: { role: 'button' }

app/views/home/index.html.haml
= link_to 'Add Record', new_air_monitor_database_url, data: {role: 'button'}
= link_to 'View Records', air_monitor_databases_url, data: {role: 'button'}

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!-- Include meta tag to ensure proper rendering and touch zooming -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Include jQuery Mobile stylesheets -->
  <link rel="stylesheet" href="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.css">
  <!-- Include the jQuery library -->
  <script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
  <!-- Include the jQuery Mobile library -->
  <script src="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"></script>
</head>
<body>

<div data-role="page" id="pageone">
  <div data-role="header">
  <%= link_to 'Home', home_url, "data-icon" => 'home' %>
  <h1>Clean Air San Francisco</h1>
  </div>

  <div data-role="main" class="ui-content">
  <%= yield %>
  </div>

  <div data-role="footer" data-position="fixed">
  <h1>AEW ENGINEERING</h1>
  </div>
</div> 

</body>
</html>